version: '3.8'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chungtm
      - POSTGRES_ADDRESS=db:5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_DRIVER_NAME=postgres
    tty: true
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - learning

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chungtm
    ports:
      - '5432:5432'
    networks:
      - learning

networks:
  learning:
    driver: bridge